import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function PdfExport({ codes, payer, provider, total, rates, codeLabels }) {
  const handleExport = () => {
    const doc = new jsPDF();
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10);

    // Header
    doc.setFontSize(18);
    doc.setTextColor(255, 130, 0); // #FF8200
    doc.text('Tristar Physical Therapy', 14, 20);
    doc.setFontSize(13);
    doc.text('Reimbursement Summary', 14, 28);

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Date: ${dateStr}`, 14, 38);

    let y = 44;

    // Provider
    if (provider) {
      doc.text(`Provider: ${provider}`, 14, y);
      y += 6;
    }

    // Payer
    doc.text(`Payer: ${payer}`, 14, y);
    y += 10;

    // Table
    const rows = codes.map(code => {
      const rate = (rates[code] || {})[payer] || 0;
      return [code, codeLabels[code] || '', rate > 0 ? `$${rate.toFixed(2)}` : 'Not covered'];
    });

    autoTable(doc, {
      startY: y,
      head: [['Code', 'Description', 'Rate']],
      body: rows,
      foot: [['', 'Total', `$${total.toFixed(2)}`]],
      headStyles: { fillColor: [255, 130, 0], textColor: 255, fontStyle: 'bold' },
      footStyles: { fillColor: [245, 245, 245], textColor: [30, 30, 30], fontStyle: 'bold' },
      styles: { fontSize: 10 },
      columnStyles: {
        0: { cellWidth: 30 },
        2: { cellWidth: 30, halign: 'right' },
      },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Tristar PT Reimbursement Calculator', 14, pageHeight - 12);

    doc.save(`tristar-visit-${dateStr}.pdf`);
  };

  return (
    <button className="btn btn-ghost btn-sm" onClick={handleExport}>
      Export PDF
    </button>
  );
}
